### ISSUE TITLE
Forms

### ISSUE THREAD

**Issue by shalakhin** [cbrauckmuller/helium#1]
Great lightweight framework. Could you add forms support here?

**Comment by cbrauckmuller** [comment]
If you check further down the readme, you'll see that Helium does have rather robust forms support. If you clone the repo and pop open forms.html you'll see a little demo of some of what's possible with the forms!

**Comment by peaceofcode** [comment]
Great work! We are using it in new customer projects.

**Comment by shalakhin** [comment]
Oh, I found. Thanks man! :) I like helium too.
