### ISSUE TITLE
Using defaults for config.rb

### ISSUE THREAD

**Issue by stephenway** [cbrauckmuller/helium#4]
Using defaults in config.rb would simplify the setup and require less code. Thoughts?

**Comment by cbrauckmuller** [comment]
You're absolutely correct. The config.rb was a holdover from when I was compiling using the alpha version of Sass that wasn't included in Codekit and needed to point Codekit to that alternative version of Sass. Would I be able to remove the config.rb file altogether?

**Comment by stephenway** [comment]
As long as the directory gets changed from `scss` to `sass` I don't believe you need to include config.rb. However for the sake of the user I would suggest including a default version (usually 2-3 lines) so they have one less thing to do after cloning, then they can customize it.
